name: Build and Push Multi-Arch Linux Image

on:
  workflow_dispatch: # for manual trigger on github
  push:
    branches: [ "lester-dev", "image-release" ]
    tags:
      - "v*"  # for triggering with versioning 
      - "build-*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | \
             docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & push multi-arch image
        run: |
          # "github.ref_name" is the tag, e.g. "v1.0.0"
          # We'll tag the image with the exact tag, plus "latest".
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact-base-image:${{ github.ref_name }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact-base-image:latest \
            --push \
            .
