name: Build and Push Multi-Arch Linux Image

on:
  workflow_dispatch: # for manual trigger on github
  push:
    branches: [ "image-release" ]
    tags:
      - "v*"  # for triggering with versioning 
      - "build-*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & push multi-arch image with cache
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --cache-from=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/refact-multiarch:cache \
            --cache-to=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/refact-multiarch:cache,mode=max \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact-multiarch:${{ github.ref_name }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact-multiarch:latest \
            .

