name: Build and Push Multi-Arch Linux Image

on:
  workflow_dispatch: # for manual trigger on github
  push:
    tags:
      - "v*"  # for triggering with versioning 
      - "build-*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | \
             docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & push multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact-base-image:${{ github.ref_name }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact-base-image:latest \
            .

